### ISSUE TITLE
🛠️ 빌더 경고 수정 및 테스트 환경 설정 개선

### ISSUE THREAD

**Issue by SINHEESEOP** [samsungnomads/Backend#13]
## 📝 이슈 내용

GitHub Actions CI/CD 빌드 중 발생하는 빌더 경고, 테스트 실패 문제, 그리고 Spring Security 관련 테스트 문제를 해결했습니다.

## 🔍 문제점

1. **Member 엔티티 관련 빌더 경고**
   ```
   @Builder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default.
   ```
   - 대상 필드:
     - `private List<Filter> ownedFilters = new ArrayList<>();`
     - `private List<MemberFilter> sharedFilters = new ArrayList<>();`

2. **테스트 실패 문제**
   - `GlobalExceptionHandlerIntegrationTest` 클래스의 모든 테스트 실패
   - 테스트 실행 시 데이터베이스 연결 오류 발생
   ```
   Error creating bean with name 'dataSource' defined in class path resource
   ```

3. **Spring Security 관련 테스트 문제**
   - `GlobalExceptionHandlerIntegrationTest`에서 인증/인가 문제 발생
   - Spring Security Test 의존성 누락
   - SecurityContext가 없어 테스트 실패

### 1. Member 엔티티 빌더 경고 수정
- 컬렉션 필드에 `@Builder.Default` 어노테이션 추가
  ```java
  @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, orphanRemoval = true)
  @Builder.Default
  private List<Filter> ownedFilters = new ArrayList<>();
  
  @OneToMany(mappedBy = "member", cascade = CascadeType.ALL, orphanRemoval = true)
  @Builder.Default
  private List<MemberFilter> sharedFilters = new ArrayList<>();
  ```

### 2. 테스트 환경 설정 개선
- `application-test.yml` 파일 추가
  ```yaml
  spring:
    datasource:
      url: jdbc:h2:mem:testdb;MODE=MySQL
      username: sa
      password: 
      driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
      show-sql: true
    h2:
      console:
        enabled: true
        path: /h2-console
    security:
      user:
        name: testuser
        password: testpassword
  jwt:
    secret: TestSecretKeyTestSecretKeyTestSecretKeyTestSecretKeyTestSecretKey1234
    access-token-validity-in-seconds: 86400
    refresh-token-validity-in-seconds: 604800
  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.test.web.servlet.result: DEBUG
  ```
- H2 데이터베이스 의존성 추가
  ```gradle
  testRuntimeOnly 'com.h2database:h2'
  ```

### 3. GlobalExceptionHandlerIntegrationTest 클래스 수정
- Spring Security Test 의존성 추가
  ```gradle
  testImplementation 'org.springframework.security:spring-security-test'
  ```
- 테스트 클래스 개선:
  ```java
  package com.samsungnomads.wheretogo.global.error;

  import org.junit.jupiter.api.DisplayName;
  import org.junit.jupiter.api.Test;
  import org.springframework.beans.factory.annotation.Autowired;
  import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
  import org.springframework.context.annotation.Import;
  import org.springframework.security.test.context.support.WithMockUser;
  import org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers;
  import org.springframework.test.context.ActiveProfiles;
  import org.springframework.test.web.servlet.MockMvc;
  import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
  import org.springframework.test.web.servlet.setup.MockMvcBuilders;
  import org.springframework.web.context.WebApplicationContext;
  import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;

  import static org.hamcrest.Matchers.is;
  import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
  import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
  import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

  /**
   * 글로벌 예외 처리 통합 테스트
   * 🧪 실제 HTTP 요청 시나리오에서 예외 처리 동작 검증
   */
  @WebMvcTest(TestExceptionController.class)
  @Import({GlobalExceptionHandler.class})
  @ActiveProfiles("test") // 테스트 프로파일 활성화 🧪
  class GlobalExceptionHandlerIntegrationTest {

      @Autowired
      private MockMvc mockMvc;

      @Test
      @WithMockUser // 인증된 사용자로 테스트 실행 🔐
      @DisplayName("비즈니스 예외 발생시 적절한 오류 응답을 반환한다")
      void handleBusinessException() throws Exception {
          // when & then
          mockMvc.perform(MockMvcRequestBuilders.get("/test/business-exception")
                  .with(csrf())) // CSRF 토큰 추가 🔒
                  .andDo(print()) // 🔍 응답 내용 출력하여 디버깅 용이하게 함
                  .andExpect(status().isBadRequest())
                  .andExpect(jsonPath("$.code", is("C001")))
                  .andExpect(jsonPath("$.message", is("잘못된 입력값입니다")))
                  .andExpect(jsonPath("$.status", is(400)));
      }

      @Test
      @WithMockUser // 인증된 사용자로 테스트 실행 🔐
      @DisplayName("엔티티 조회 실패 예외 발생시 적절한 오류 응답을 반환한다")
      void handleEntityNotFoundException() throws Exception {
          // when & then
          mockMvc.perform(MockMvcRequestBuilders.get("/test/entity-not-found/123")
                  .with(csrf())) // CSRF 토큰 추가 🔒
                  .andDo(print()) // 🔍 응답 내용 출력하여 디버깅 용이하게 함
                  .andExpect(status().isNotFound())
                  .andExpect(jsonPath("$.code", is("M002")))
                  .andExpect(jsonPath("$.message", is("회원을 찾을 수 없습니다. ID: 123")))
                  .andExpect(jsonPath("$.status", is(404)));
      }

      @Test
      @WithMockUser // 인증된 사용자로 테스트 실행 🔐
      @DisplayName("처리되지 않은 예외 발생시 서버 오류 응답을 반환한다")
      void handleUnexpectedException() throws Exception {
          // when & then
          mockMvc.perform(MockMvcRequestBuilders.get("/test/unexpected-exception")
                  .with(csrf())) // CSRF 토큰 추가 🔒
                  .andDo(print()) // 🔍 응답 내용 출력하여 디버깅 용이하게 함
                  .andExpect(status().isInternalServerError())
                  .andExpect(jsonPath("$.code", is("C004")))
                  .andExpect(jsonPath("$.message", is("서버 내부 오류가 발생했습니다")))
                  .andExpect(jsonPath("$.status", is(500)));
      }
  }
  ```

### 4. GitHub Actions 워크플로우 파일 수정
- 테스트 환경 설정 파일 자동 생성 단계 추가
  ```yaml
  - name: make test configuration
    run: |
      mkdir -p ./src/test/resources
      cd ./src/test/resources
      touch ./application-test.yml
      echo "spring:
        datasource:
          url: jdbc:h2:mem:testdb;MODE=MySQL
          username: sa
          password: 
          driver-class-name: org.h2.Driver
        jpa:
          hibernate:
            ddl-auto: create-drop
          properties:
            hibernate:
              format_sql: true
              use_sql_comments: true
          show-sql: true
        h2:
          console:
            enabled: true
            path: /h2-console
        security:
          user:
            name: testuser
            password: testpassword
      jwt:
        secret: TestSecretKeyTestSecretKeyTestSecretKeyTestSecretKeyTestSecretKey1234
        access-token-validity-in-seconds: 86400
        refresh-token-validity-in-seconds: 604800
      logging:
        level:
          org.springframework.security: DEBUG
          org.springframework.test.web.servlet.result: DEBUG" > ./application-test.yml
  ```

## 🧪 테스트 결과
- 로컬 환경에서 빌드 성공
- 모든 테스트 통과 확인
- 컴파일 경고 해결
- 보안 관련 테스트 이슈 해결
  - CSRF 토큰 추가로 인증 문제 해결
  - `@WithMockUser` 어노테이션으로 인증된 사용자 모의
  - `@ActiveProfiles("test")` 추가로 테스트 환경 분리

## 📋 관련 브랜치
- 브랜치: `shs2`
- 커밋: `acf1376`

## 📈 기대 효과
1. CI/CD 파이프라인 빌드 성공률 향상
2. 테스트 안정성 및 신뢰성 개선
3. 코드 품질 향상
4. 보안 관련 테스트 설정 개선으로 안정적인 테스트 환경 구축
